export { default as api } from './api'
export * from './citasService'
export * from './configuracionService'
export * from './dashboardService'
export * from './facturacionService'
export * from './historiaClinicaService'
export * from './pacientesService'
export * from './profesionalesService'
export * from './tratamientosService'
export * from './usuariosService'
export { default as presupuestosService } from './presupuestosService'
export { default as recetasService } from './recetasService'
export { default as laboratorioService } from './laboratorioService'
export { default as cajaService } from './cajaService'
export { default as inventarioService } from './inventarioService'
export { default as auditService } from './auditService'
export { default as consentimientosService } from './consentimientosService'
